=== folio-org/mod-erm-usage/ramls/schemas/counterreport.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Counter Report and Metadata",
  "title": "Counter Report Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "downloadTime": {
      "description": "Date and time the report was downloaded",
      "type": "string",
      "format": "date-time"
    },
    "failedAttempts": {
      "description": "Count of failed download attempts",
      "type": "integer"
    },
    "failedReason": {
      "description": "Error message from failed download attempt",
      "type": "string"
    },
    "apiExceptions": {
      "description": "One or multiple exceptions related to the failed download attempt",
      "type": "array",
      "default": null,
      "minItems": 1,
      "items": {
        "type": "object",
        "$ref": "exception.json"
      }
    },
    "release": {
      "description": "Counter Report version",
      "type": "string"
    },
    "reportName": {
      "description": "Counter Report name",
      "type": "string"
    },
    "yearMonth": {
      "description": "Counter Report period (one month)",
      "type": "string",
      "format": "date-month"
    },
    "providerId": {
      "description": "Provider identifier",
      "type": "string"
    },
    "report": {
      "description": "Actual counter report data",
      "type": "object"
    },
    "metadata": {
      "description": "Metadata about creation and changes, provided by the server (client should not provide)",
      "type": "object",
      "$ref": "../raml-util/schemas/metadata.schema",
      "readonly": true
    },
    "reportEditedManually": {
      "description": "Report data has been edited manually",
      "type": "boolean"
    },
    "editReason": {
      "description": "Edit reason",
      "type": "string"
    }
  },
  "required": [
    "downloadTime",
    "release",
    "reportName",
    "yearMonth"
  ],
  "additionalProperties": true
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/2018-03.json
{
  "id": "2433dfef-47de-48ac-8124-869329363ec2",
  "downloadTime": "2019-04-12T13:33:32.919+0000",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2018-03",
  "providerId": "e67924ee-aa00-454e-8fd0-c3f81339d20e",
  "report": {
    "vendor": {
      "id": "This is a fake vendor",
      "contact": [
      ]
    },
    "created": "2019-02-27T10:21:56.000+01:00",
    "name": "JR1",
    "id": "17:67:17:2018-03-01:2018-03-31",
    "title": "Journal Report 1",
    "version": "4",
    "customer": [
      {
        "id": "FAKE CUSTOMER ID",
        "contact": [
        ],
        "reportItems": [
          {
            "itemDate": [
            ],
            "itemName": "The cats journal",
            "itemDataType": "JOURNAL",
            "itemPlatform": "platform.com",
            "itemAttribute": [
            ],
            "itemPublisher": "Cats and Dogs Publishing",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.10XX"
              },
              {
                "type": "PROPRIETARY",
                "value": "XXX"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1111-2222"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "3333-4444"
              }
            ],
            "itemContributor": [
            ],
            "itemPerformance": [
              {
                "period": {
                  "end": "2018-03-31",
                  "begin": "2018-03-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 18,
                    "metricType": "FT_TOTAL"
                  },
                  {
                    "count": 8,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 10,
                    "metricType": "FT_HTML"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [
            ],
            "itemName": "The dogs journal",
            "itemDataType": "JOURNAL",
            "itemPlatform": "platform.com",
            "itemAttribute": [
            ],
            "itemPublisher": "Cats and Dogs Publishing",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.10YY"
              },
              {
                "type": "PROPRIETARY",
                "value": "YYY"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1111-2222"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "3333-4444"
              }
            ],
            "itemContributor": [
            ],
            "itemPerformance": [
              {
                "period": {
                  "end": "2018-03-31",
                  "begin": "2018-03-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  },
                  {
                    "count": 0,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_HTML"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [
            ],
            "itemName": "Cats and Dogs",
            "itemDataType": "JOURNAL",
            "itemPlatform": "platform.com",
            "itemAttribute": [
            ],
            "itemPublisher": "Cats and Dogs Publishing",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.10ZZ"
              },
              {
                "type": "PROPRIETARY",
                "value": "ZZZ"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1111-2222"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "3333-4444"
              }
            ],
            "itemContributor": [
            ],
            "itemPerformance": [
              {
                "period": {
                  "end": "2018-03-31",
                  "begin": "2018-03-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 0,
                    "metricType": "FT_TOTAL"
                  },
                  {
                    "count": 0,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 0,
                    "metricType": "FT_HTML"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [
            ],
            "itemName": "Why do not cats and dogs like each other",
            "itemDataType": "JOURNAL",
            "itemPlatform": "platform.com",
            "itemAttribute": [
            ],
            "itemPublisher": "Cats and Dogs Publishing",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.10??"
              },
              {
                "type": "PROPRIETARY",
                "value": "???"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1111-2222"
              }
            ],
            "itemContributor": [
            ],
            "itemPerformance": [
              {
                "period": {
                  "end": "2018-03-31",
                  "begin": "2018-03-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 12,
                    "metricType": "FT_TOTAL"
                  },
                  {
                    "count": 11,
                    "metricType": "FT_HTML"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [
            ],
            "itemName": "What if cats and dogs liked each other",
            "itemDataType": "JOURNAL",
            "itemPlatform": "platform.com",
            "itemAttribute": [
            ],
            "itemPublisher": "Cats and Dogs Publishing",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.10!!!"
              },
              {
                "type": "PROPRIETARY",
                "value": "!!!"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1111-2222"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "3333-4444"
              }
            ],
            "itemContributor": [
            ],
            "itemPerformance": [
              {
                "period": {
                  "end": "2018-03-31",
                  "begin": "2018-03-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 10,
                    "metricType": "FT_HTML"
                  },
                  {
                    "count": 4,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 14,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": [
        ]
      }
    ],
    "reportEditedManually": false,
    "editReason": ""
  }
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/d5-d32-R4-JR1-2019-03.json
{
  "id": "63e205e3-9f86-4a00-a44f-3b143440eb2f",
  "downloadTime": "2020-06-11T01:24:00.947+00:00",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-03",
  "providerId": "d54f9d37-7759-44b6-a621-f950e6332d32",
  "report": {
    "vendor": {
      "id": "https://www.inderscienceonline.com",
      "name": "Inderscience Publishers",
      "contact": [
        {
          "email": "jrb@inderscience.com",
          "contact": "Inderscience Publishers"
        }
      ],
      "webSiteUrl": "https://www.inderscienceonline.com"
    },
    "created": "2020-06-10T18:04:00.000Z",
    "name": "JR1",
    "id": "www.inderscienceonline.com_journal1",
    "title": "Journal Report 1",
    "version": "4",
    "customer": [
      {
        "id": "123-45-678",
        "name": "CustomerName",
        "contact": [],
        "reportItems": [
          {
            "itemDate": [],
            "itemName": "International Journal of Comparative Management",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijcm"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijcm"
              },
              {
                "type": "PRINT_ISSN",
                "value": "2514-4111"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "2514-412X"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-03-31",
                  "begin": "2019-03-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": []
      }
    ]
  }
}
