=== folio-org/mod-erm-usage/ramls/schemas/counterreport.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Counter Report and Metadata",
  "title": "Counter Report Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "downloadTime": {
      "description": "Date and time the report was downloaded",
      "type": "string",
      "format": "date-time"
    },
    "failedAttempts": {
      "description": "Count of failed download attempts",
      "type": "integer"
    },
    "failedReason": {
      "description": "Error message from failed download attempt",
      "type": "string"
    },
    "apiExceptions": {
      "description": "One or multiple exceptions related to the failed download attempt",
      "type": "array",
      "default": null,
      "minItems": 1,
      "items": {
        "type": "object",
        "$ref": "exception.json"
      }
    },
    "release": {
      "description": "Counter Report version",
      "type": "string"
    },
    "reportName": {
      "description": "Counter Report name",
      "type": "string"
    },
    "yearMonth": {
      "description": "Counter Report period (one month)",
      "type": "string",
      "format": "date-month"
    },
    "providerId": {
      "description": "Provider identifier",
      "type": "string"
    },
    "report": {
      "description": "Actual counter report data",
      "type": "object"
    },
    "metadata": {
      "description": "Metadata about creation and changes, provided by the server (client should not provide)",
      "type": "object",
      "$ref": "../raml-util/schemas/metadata.schema",
      "readonly": true
    },
    "reportEditedManually": {
      "description": "Report data has been edited manually",
      "type": "boolean"
    },
    "editReason": {
      "description": "Edit reason",
      "type": "string"
    }
  },
  "required": [
    "downloadTime",
    "release",
    "reportName",
    "yearMonth"
  ],
  "additionalProperties": true
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/63-d71-R51-IR-2021-10.json
{
  "id" : "d97e25d7-4529-4864-ac85-66cc7633ce94",
  "downloadTime" : "2025-02-04T14:03:25.448+00:00",
  "failedAttempts" : 5,
  "failedReason" : "{\"Code\":3032,\"Message\":\"Usage no longer available for requested dates\",\"Help_URL\":\"http://example.com\",\"Data\":\"No usage data prior to Jan 2022 is available\"}",
  "apiExceptions" : [ {
    "code" : 3032,
    "message" : "Usage no longer available for requested dates",
    "helpUrl" : "http://example.com",
    "data" : "No usage data prior to Jan 2022 is available"
  } ],
  "release" : "5.1",
  "reportName" : "IR",
  "yearMonth" : "2021-10",
  "providerId" : "63c056c2-9e56-4148-8002-2a8649827d71"
}

=== folio-org/mod-erm-usage/mod-erm-usage-server/src/test/resources/JR1/jr1_2.json
{
  "downloadTime": "2019-02-01T08:00:00.000+0000",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-02",
  "providerId": "4b659cb9-e4bb-493d-ae30-5f5690c54802",
  "report": {
    "vendor": {
      "id": "SEM001",
      "name": "Semantico Ltd.",
      "contact": [],
      "logoUrl": "http://www.semantico.com/wp-content/themes/semantico/images/logo-new.png",
      "webSiteUrl": "http://www.semantico.com"
    },
    "created": "2019-02-01T00:40:50.994Z",
    "name": "Journal Report 1 (R4)",
    "id": "1549010450995",
    "title": "JR1:4",
    "version": "4",
    "customer": [
      {
        "id": "customerId123",
        "contact": [],
        "reportItems": [
          {
            "itemDate": [],
            "itemName": "19th-Century Music",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Ithaka",
            "itemAttribute": [],
            "itemPublisher": "University of California Press",
            "itemIdentifier": [
              {
                "type": "ONLINE_ISSN",
                "value": "1533-8606"
              },
              {
                "type": "PRINT_ISSN",
                "value": "0148-2076"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-02-28",
                  "begin": "2019-02-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_HTML"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 2,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": []
      }
    ]
  }
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/d5-d32-R4-JR1-2019-04.json
{
  "id": "39434d0e-2462-4c15-9ce5-84f7be516a07",
  "downloadTime": "2020-06-11T01:24:00.948+00:00",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-04",
  "providerId": "d54f9d37-7759-44b6-a621-f950e6332d32",
  "report": {
    "vendor": {
      "id": "https://www.inderscienceonline.com",
      "name": "Inderscience Publishers",
      "contact": [
        {
          "email": "jrb@inderscience.com",
          "contact": "Inderscience Publishers"
        }
      ],
      "webSiteUrl": "https://www.inderscienceonline.com"
    },
    "created": "2020-06-10T18:05:00.000Z",
    "name": "JR1",
    "id": "www.inderscienceonline.com_journal1",
    "title": "Journal Report 1",
    "version": "4",
    "customer": [
      {
        "id": "123-45-678",
        "name": "CustomerName",
        "contact": [],
        "reportItems": [
          {
            "itemDate": [],
            "itemName": "International Journal of Web Based Communities",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijwbc"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijwbc"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1477-8394"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "1741-8216"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-04-30",
                  "begin": "2019-04-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": []
      }
    ]
  }
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/d5-d32-R4-JR1-2019-10.json
{
  "id": "06d79d97-2a70-4d8e-8262-7608bb846085",
  "downloadTime": "2020-07-09T01:08:05.232+00:00",
  "failedAttempts": 5,
  "failedReason": "Report not valid: Exception{Number=3030, Severity=ERROR, Message=No Usage Available for Requested Dates}",
  "apiExceptions": [
    {
      "code": 3030,
      "message": "No Usage Available for Requested Dates"
    }
  ],
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-10",
  "providerId": "d54f9d37-7759-44b6-a621-f950e6332d32"
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/d5-d32-R4-JR1-2019-08.json
{
  "id": "7b9420f5-169b-43d2-a79e-391b90e192fe",
  "downloadTime": "2020-06-11T01:24:00.947+00:00",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-08",
  "providerId": "d54f9d37-7759-44b6-a621-f950e6332d32",
  "report": {
    "vendor": {
      "id": "https://www.inderscienceonline.com",
      "name": "Inderscience Publishers",
      "contact": [
        {
          "email": "jrb@inderscience.com",
          "contact": "Inderscience Publishers"
        }
      ],
      "webSiteUrl": "https://www.inderscienceonline.com"
    },
    "created": "2020-06-10T18:05:00.000Z",
    "name": "JR1",
    "id": "www.inderscienceonline.com_journal1",
    "title": "Journal Report 1",
    "version": "4",
    "customer": [
      {
        "id": "123-45-678",
        "name": "CustomerName",
        "contact": [],
        "reportItems": [
          {
            "itemDate": [],
            "itemName": "International Journal of Decision Sciences, Risk and Management",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijdsrm"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijdsrm"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1753-7169"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "1753-7177"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-08-31",
                  "begin": "2019-08-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [],
            "itemName": "International Journal of Digital Enterprise Technology",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijdet"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijdet"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1756-2554"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "1756-2562"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-08-31",
                  "begin": "2019-08-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [],
            "itemName": "International Journal of Electronic Business",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijeb"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijeb"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1470-6067"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "1741-5063"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-08-31",
                  "begin": "2019-08-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": []
      }
    ]
  }
}

=== folio-org/mod-erm-usage/mod-erm-usage-server/src/test/resources/TR/TR_2.json
{
  "downloadTime": "2019-03-01T08:00:00.000+0000",
  "release": "5",
  "reportName": "TR",
  "yearMonth": "2019-10",
  "providerId": "4b659cb9-e4bb-493d-ae30-5f5690c54802",
  "report": {
    "Report_Header": {
      "Customer_ID": "uuid-1234",
      "Institution_Name": "MY INSTITUION",
      "Institution_ID": [
        {
          "Type": "Proprietary",
          "Value": "mit:1234"
        }
      ],
      "Report_Filters": [
        {
          "Name": "End_Date",
          "Value": "2019-10-31"
        },
        {
          "Name": "Begin_Date",
          "Value": "2019-10-01"
        }
      ],
      "Created": "2020-03-27T11:10:41Z",
      "Created_By": "FooBar Systems",
      "Release": "5",
      "Report_Name": "Title Master Report",
      "Report_ID": "TR"
    },
    "Report_Items": [
      {
        "Platform": "My Journals",
        "Performance": [
          {
            "Period": {
              "Begin_Date": "2019-10-01",
              "End_Date": "2019-10-31"
            },
            "Instance": [
              {
                "Metric_Type": "Unique_Item_Requests",
                "Count": 4
              },
              {
                "Metric_Type": "Total_Item_Requests",
                "Count": 4
              },
              {
                "Metric_Type": "Unique_Item_Investigations",
                "Count": 4
              },
              {
                "Metric_Type": "Total_Item_Investigations",
                "Count": 4
              }
            ]
          }
        ],
        "Item_ID": [
          {
            "Type": "DOI",
            "Value": "101112.DOI"
          },
          {
            "Type": "Proprietary",
            "Value": "my:ab"
          },
          {
            "Type": "Online_ISSN",
            "Value": "1111-2222"
          },
          {
            "Type": "Print_ISSN",
            "Value": "0000-1111"
          }
        ],
        "Title": "Title 3",
        "Publisher_ID": [
          {
            "Type": "Proprietary",
            "Value": "my:mypress"
          }
        ],
        "Publisher": "My Press"
      },
      {
        "Platform": "My Journals",
        "Performance": [
          {
            "Period": {
              "Begin_Date": "2019-10-01",
              "End_Date": "2019-10-31"
            },
            "Instance": [
              {
                "Metric_Type": "Unique_Item_Requests",
                "Count": 1
              },
              {
                "Metric_Type": "Total_Item_Requests",
                "Count": 1
              },
              {
                "Metric_Type": "Unique_Item_Investigations",
                "Count": 2
              },
              {
                "Metric_Type": "Total_Item_Investigations",
                "Count": 2
              }
            ]
          }
        ],
        "Item_ID": [
          {
            "Type": "DOI",
            "Value": "111213.DOI"
          },
          {
            "Type": "Proprietary",
            "Value": "my:abc"
          },
          {
            "Type": "Online_ISSN",
            "Value": "2222-3333"
          },
          {
            "Type": "Print_ISSN",
            "Value": "0001-1112"
          }
        ],
        "Title": "Title 4",
        "Publisher_ID": [
          {
            "Type": "Proprietary",
            "Value": "my:mypress"
          }
        ],
        "Publisher": "My Press"
      },
      {
        "Platform": "My Journals",
        "Performance": [
          {
            "Period": {
              "Begin_Date": "2019-10-01",
              "End_Date": "2019-10-31"
            },
            "Instance": [
              {
                "Metric_Type": "Unique_Item_Requests",
                "Count": 2
              },
              {
                "Metric_Type": "Total_Item_Requests",
                "Count": 2
              },
              {
                "Metric_Type": "No_License",
                "Count": 8
              },
              {
                "Metric_Type": "Unique_Item_Investigations",
                "Count": 11
              },
              {
                "Metric_Type": "Total_Item_Investigations",
                "Count": 14
              }
            ]
          }
        ],
        "Item_ID": [
          {
            "Type": "DOI",
            "Value": "121314.DOI"
          },
          {
            "Type": "Proprietary",
            "Value": "my:abcd"
          },
          {
            "Type": "Online_ISSN",
            "Value": "3333-4444"
          },
          {
            "Type": "Print_ISSN",
            "Value": "0002-1113"
          }
        ],
        "Title": "Title 5",
        "Publisher_ID": [
          {
            "Type": "Proprietary",
            "Value": "my:mypress"
          }
        ],
        "Publisher": "My Press"
      }
    ]
  }
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/d5-d32-R4-JR1-2019-01.json
{
  "id": "1ad95437-4f1b-4f3b-9654-622ff28d271d",
  "downloadTime": "2020-06-11T01:24:00.948+00:00",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-01",
  "providerId": "d54f9d37-7759-44b6-a621-f950e6332d32",
  "report": {
    "vendor": {
      "id": "https://www.inderscienceonline.com",
      "name": "Inderscience Publishers",
      "contact": [
        {
          "email": "jrb@inderscience.com",
          "contact": "Inderscience Publishers"
        }
      ],
      "webSiteUrl": "https://www.inderscienceonline.com"
    },
    "created": "2020-06-10T18:04:00.000Z",
    "name": "JR1",
    "id": "www.inderscienceonline.com_journal1",
    "title": "Journal Report 1",
    "version": "4",
    "customer": [
      {
        "id": "123-45-678",
        "name": "CustomerName",
        "contact": [],
        "reportItems": [
          {
            "itemDate": [],
            "itemName": "International Journal of Internet of Things and Cyber-Assurance",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijitca"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijitca"
              },
              {
                "type": "PRINT_ISSN",
                "value": "2059-7967"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "2059-7975"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-01-31",
                  "begin": "2019-01-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          },
          {
            "itemDate": [],
            "itemName": "International Journal of Supply Chain and Operations Resilience",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/ijscor"
              },
              {
                "type": "PROPRIETARY",
                "value": "ijscor"
              },
              {
                "type": "PRINT_ISSN",
                "value": "2052-868X"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "2052-8698"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-01-31",
                  "begin": "2019-01-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 2,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 2,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": []
      }
    ]
  }
}

=== folio-org/mod-erm-usage/sample-data/counter-reports/d5-d32-R4-JR1-2019-02.json
{
  "id": "13dac374-99e3-4f24-a2b9-7c5712fbda00",
  "downloadTime": "2020-06-11T01:24:00.947+00:00",
  "release": "4",
  "reportName": "JR1",
  "yearMonth": "2019-02",
  "providerId": "d54f9d37-7759-44b6-a621-f950e6332d32",
  "report": {
    "vendor": {
      "id": "https://www.inderscienceonline.com",
      "name": "Inderscience Publishers",
      "contact": [
        {
          "email": "jrb@inderscience.com",
          "contact": "Inderscience Publishers"
        }
      ],
      "webSiteUrl": "https://www.inderscienceonline.com"
    },
    "created": "2020-06-10T18:04:00.000Z",
    "name": "JR1",
    "id": "www.inderscienceonline.com_journal1",
    "title": "Journal Report 1",
    "version": "4",
    "customer": [
      {
        "id": "123-45-678",
        "name": "CustomerName",
        "contact": [],
        "reportItems": [
          {
            "itemDate": [],
            "itemName": "Progress in Industrial Ecology, an International Journal",
            "itemDataType": "JOURNAL",
            "itemPlatform": "Inderscience Publishers",
            "itemAttribute": [],
            "itemPublisher": "Inderscience Publishers",
            "itemIdentifier": [
              {
                "type": "DOI",
                "value": "10.1504/pie"
              },
              {
                "type": "PROPRIETARY",
                "value": "pie"
              },
              {
                "type": "PRINT_ISSN",
                "value": "1476-8917"
              },
              {
                "type": "ONLINE_ISSN",
                "value": "1478-8764"
              }
            ],
            "itemContributor": [],
            "itemPerformance": [
              {
                "period": {
                  "end": "2019-02-28",
                  "begin": "2019-02-01"
                },
                "category": "REQUESTS",
                "instance": [
                  {
                    "count": 1,
                    "metricType": "FT_PDF"
                  },
                  {
                    "count": 1,
                    "metricType": "FT_TOTAL"
                  }
                ]
              }
            ]
          }
        ],
        "institutionalIdentifier": []
      }
    ]
  }
}
