=== folio-org/mod-erm-usage/ramls/schemas/udprovider.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Usage Data Provider Schema",
  "title": "Usage Data Provider Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "label": {
      "description": "Usage Data Provider name",
      "type": "string"
    },
    "description": {
      "description": "Usage Data Provider description",
      "type": "string"
    },
    "status": {
      "description": "Status of the Usage Data Provider",
      "type": "string",
      "enum": [
        "active",
        "inactive"
      ],
      "default": "active"
    },
    "harvestingConfig": {
      "type": "object",
      "description": "Specifies harvesting configuration",
      "properties": {
        "harvestingStatus": {
          "description": "Enables or disables automatic harvesting for this provider",
          "type": "string",
          "enum": [
            "active",
            "inactive"
          ]
        },
        "harvestVia": {
          "type": "string",
          "description": "Specifies how to harvest usage data, from a provider via Sushi.",
          "enum": [
            "sushi"
          ]
        },
        "sushiConfig": {
          "description": "SUSHI service properties",
          "type": "object",
          "properties": {
            "serviceType": {
              "type": "string",
              "description": "Type of SUSHI service (i.e. cs41 for Counter-Sushi 4.1) for direct harvesting (see /erm-usage-harvester/impl)."
            },
            "serviceUrl": {
              "type": "string",
              "description": "SUSHI service URL to access provider's SUSHI service."
            }
          }
        },
        "reportRelease": {
          "type": "string",
          "description": "Specifies the counter report version."
        },
        "requestedReports": {
          "description": "Report types that are harvested. Note, types differ between counter 4 and counter 5.",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "string"
          }
        },
        "harvestingStart": {
          "description": "First month getting harvested",
          "type": "string",
          "format": "date-month"
        },
        "harvestingEnd": {
          "description": "Last month getting harvested",
          "type": "string",
          "format": "date-month"
        }
      },
      "required": [
        "harvestingStatus"
      ]
    },
    "sushiCredentials": {
      "type": "object",
      "description": "Defines credentials to access SUSHI service of usage data provider",
      "properties": {
        "customerId": {
          "description": "Customer identifier",
          "type": "string"
        },
        "requestorId": {
          "description": "Requestor identifier",
          "type": "string"
        },
        "apiKey": {
          "description": "API Key",
          "type": "string"
        },
        "platform": {
          "description": "Name of the Platform the usage is being requested for",
          "type": "string"
        },
        "requestorName": {
          "description": "Requestor name",
          "type": "string"
        },
        "requestorMail": {
          "description": "Requestor mail",
          "type": "string"
        }
      }
    },
    "latestReport": {
      "description": "Newest report available for provider",
      "type": "string"
    },
    "earliestReport": {
      "description": "Oldest report available for provider",
      "type": "string"
    },
    "hasFailedReport": {
      "description": "Indicator if this provider has a failed report",
      "type": "string",
      "enum": [
        "yes",
        "no"
      ],
      "default": "no"
    },
    "reportErrorCodes": {
      "description": "Counter report error codes of reports associated with this UDP",
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "reportTypes": {
      "description": "Counter report types of reports associated with this UDP",
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "reportReleases": {
      "description": "Counter report release versions of reports associated with this UDP",
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "harvestingDate": {
      "description": "Date and time of the last harvesting attempt",
      "type": "string",
      "format": "date-time"
    },
    "notes": {
      "description": "Notes for provider",
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "$ref": "../raml-util/schemas/metadata.schema"
    },
    "tags": {
      "type": "object",
      "$ref": "../raml-util/schemas/tags.schema"
    }
  },
  "required": [
    "label",
    "status",
    "harvestingConfig"
  ],
  "additionalProperties": true
}

=== folio-org/mod-erm-usage/sample-data/usage-data-providers/SAMPLE_R51.json
{
  "id": "63c056c2-9e56-4148-8002-2a8649827d71",
  "label": "Sample Provider R5.1",
  "status": "active",
  "harvestingConfig": {
    "harvestingStatus": "active",
    "sushiConfig": {
      "serviceType": "cs51",
      "serviceUrl": "https://localhost/sample"
    },
    "reportRelease": "5.1",
    "requestedReports": [
      "TR",
      "IR",
      "PR",
      "DR"
    ],
    "harvestingStart": "2021-01",
    "harvestingEnd": "2022-12"
  },
  "sushiCredentials": {
    "customerId": "abc123"
  },
  "notes": "Provider with sample data for COUNTER 5 and COUNTER 5.1 reports."
}
